# Generated by Django 4.2 on 2023-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
