# Generated by Django 4.2 on 2023-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_image_url_image_image_image_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='places', verbose_name='Фотография'),
        ),
    ]
