# Generated by Django 4.2 on 2023-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['priority'], 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Приоритет'),
        ),
    ]
